apiVersion: apps/v1
kind: Deployment
metadata:
  name: torii-deployment
  labels:
    app: torii
spec:
  replicas: 1
  selector:
    matchLabels:
      app: torii
  template:
    metadata:
      labels:
        app: torii
    spec:
      containers:
        - name: torii
          image: localhost:32000/torii:0.0.4
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: torii-service
spec:
  selector:
    app: torii
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
