name: K8s -> Deploy
description: Deploys Kubernetes

inputs:
  file:
    description: The Kubernetes file to deploy
    required: true

runs:
  using: composite
  steps:
    - name: Deploy
      if: github.ref_name == 'main'
      shell: bash
      run: |
        microk8s kubectl apply -f ${{ inputs.file }}
        microk8s kubectl rollout status deployment/torii-deployment --watch=true --timeout=60s
