name: Infrastructure -> Test
description: Tests the infrastructure

inputs:
  kubernetes-file:
    description: The Kubernetes file to test
    required: true

runs:
  using: composite
  steps:
    - name: Kubectl diff
      # The diff command returns an error code when there are changes, without the {0} the whole step is marked as failed
      shell: bash {0}
      run: |
        diff=`microk8s kubectl diff -f ${{ inputs.kubernetes-file }}`
        echo $diff
        {
          echo 'KUBECTL_DIFF<<EOF'
          echo "$diff"
          echo EOF
        } >> "$GITHUB_ENV"

    - name: PR comment diff
      if: github.ref_name != 'main'
      uses: marocchino/sticky-pull-request-comment@5ec44f8ee5ecf07ea2e7410866738fb7890eb756
      with:
        message: |
          ## kubectl diff 
          <details>
            <summary>Show diff</summary>

            ```diff
            ${{ env.KUBECTL_DIFF }}
            ```

          </details>

    - name: Kubectl dry-run
      shell: bash
      run: microk8s kubectl apply -f ${{ inputs.kubernetes-file }} --dry-run=server
