name: Build and Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.ref || github.run_id }}
  cancel-in-progress: true

env:
  DOCKER_REGISTRY: localhost:32000
  DOCKER_IMAGE_NAME: localhost:32000/torii

jobs:
  build-deploy:
    name: Build and Deploy
    runs-on: self-hosted
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.7.0

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Image Metadata
        id: image-metadata
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_IMAGE_NAME }}
          tags: type=sha

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}

      - name: Create Docker Image
        uses: docker/build-push-action@v5
        with:
          push: true
          context: .
          tags: ${{ steps.image-metadata.outputs.tags }}
          labels: ${{ steps.image-metadata.outputs.labels }}

      - name: Set version to deploy in k8s.yaml
        run: sed -i -E "s/torii:version/torii:${{ steps.image-metadata.outputs.version }}/g" k8s.yaml

      - name: Deploy
        run: |
          microk8s kubectl apply -f k8s.yaml
          microk8s kubectl rollout status deployment/torii-deployment --watch=true --timeout=60s
