name: Next.js

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.ref || github.run_id }}
  cancel-in-progress: true

env:
  SERVICE_IMAGE_NAME: localhost:32000/torii${{ github.ref_name != 'main' && '-pr' || '' }}

jobs:
  test-solution:
    name: Solution -> Test
    runs-on: ubuntu-latest
    outputs:
      node-version: ${{ steps.solution.outputs.node-version }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Solution -> Test
        id: solution
        uses: ./.github/actions/test-solution

  publish-service-image:
    name: Service Image -> Publish
    needs: [test-solution]
    runs-on: self-hosted
    outputs:
      image-sha-tag: ${{ steps.image.outputs.image-sha-tag }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Service Image -> Publish
        id: image
        uses: ./.github/actions/publish-image
        with:
          dockerfile-path: ./Dockerfile
          image-name: ${{ env.SERVICE_IMAGE_NAME }}
          build-args: NODE_VERSION=${{ needs.test-solution.outputs.node-version }}

  deploy-service:
    name: Service -> Deploy ${{ github.ref_name != 'main' && '(Plan Only)' || '' }}
    needs: [publish-service-image]
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Service -> Deploy
        uses: ./.github/actions/deploy-service
        with:
          image-name: ${{ needs.publish-service-image.outputs.image-sha-tag }}
          deploy: ${{ github.ref_name == 'main' }}
